---
services:
  traefik:
    command: --log.level=error
    image: traefik:2.3
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config-files:/etc/traefik
    networks:
      - traefik_reverse_proxy
      - default
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  bitwarden:
    image: vaultwarden/server:1.22.1
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /var/docker/bitwarden:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-https.redirectScheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectScheme.permanent=true"
      - "traefik.http.routers.bitwarden-ui-https.rule=Host(`${BITWARDEN_URL}`)"
      - "traefik.http.routers.bitwarden-ui-https.entrypoints=web-secure"
      - "traefik.http.routers.bitwarden-ui-https.tls=true"
      - "traefik.http.routers.bitwarden-ui-https.service=bitwarden-ui"
      - "traefik.http.routers.bitwarden-ui-http.rule=Host(`${BITWARDEN_URL}`)"
      - "traefik.http.routers.bitwarden-ui-http.entrypoints=web"
      - "traefik.http.routers.bitwarden-ui-http.middlewares=redirect-https"
      - "traefik.http.routers.bitwarden-ui-http.service=bitwarden-ui"
      - "traefik.http.services.bitwarden-ui.loadbalancer.server.port=80"
      - "traefik.http.routers.bitwarden-admin.rule=Host(`${BITWARDEN_URL}`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.bitwarden-admin.entrypoints=web-secure"
      - "traefik.http.routers.bitwarden-admin.tls=true"
      - "traefik.http.routers.bitwarden-admin.service=admin-panel"
      - "traefik.http.services.admin-panel.loadbalancer.server.port=80"
      - "traefik.http.routers.bitwarden-admin.tls.certresolver=default"
      - "traefik.http.middlewares.admin-auth.basicauth.users=user:password" #'user:password' ersetzen.
      - "traefik.http.routers.bitwarden-admin.middlewares=admin-auth"
      - "traefik.http.routers.bitwarden-ui-https.middlewares=secHeaders@file"
      - "traefik.http.routers.bitwarden-websocket-https.rule=Host(`${BITWARDEN_URL}`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-websocket-https.entrypoints=web-secure"
      - "traefik.http.routers.bitwarden-websocket-https.tls=true"
      - "traefik.http.routers.bitwarden-websocket-https.service=bitwarden-websocket"
      - "traefik.http.routers.bitwarden-websocket-http.rule=Host(`${BITWARDEN_URL}`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-websocket-http.entrypoints=web"
      - "traefik.http.routers.bitwarden-websocket-http.middlewares=redirect-https"
      - "traefik.http.routers.bitwarden-websocket-http.service=bitwarden-websocket"
      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"
    environment:
      - "ADMIN_TOKEN=${ADMIN_TOKEN}"
      - "WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED}"
    networks:
      - traefik_reverse_proxy

networks:
  traefik_reverse_proxy:
    external:
      name: traefik_reverse_proxy
  default:
    driver: bridge
